apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  namespace: {{ .Release.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: jaeger
  namespace: {{ .Release.namespace }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - jaeger-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jaeger
  namespace: {{ .Release.namespace }}
subjects:
  - kind: ServiceAccount
    name: jaeger
  - kind: ServiceAccount
    name: jaeger-collector
  - kind: ServiceAccount
    name: jaeger-query
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jaeger
---
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: jaeger
  namespace: {{ .Release.namespace }}
spec:
  strategy: allInOne
  storage:
    options:
      memory:
        max-traces: 100